- hosts: localhost
  tasks:
    - name: Install Node.js
      apt:
        name: nodejs
        state: latest

    - name: Install npm
      apt:
        name: npm
        state: latest

    - name: Create a sample application
      template:
        src: templates/app.js.j2
        dest: /home/ubuntu/app.js

    - name: Install pm2
      npm:
        name: pm2
        global: yes
        state: present

    - name: Run node app
      shell: pm2 start /home/ubuntu/app.js
