all:
    hosts:
    children:
        mongodb:
            hosts:
                ec2-52-29-21-17.eu-central-1.compute.amazonaws.com:
                    host_name: mongo-1
                    host_ip: "52.29.21.17"
                    host_private_ip: "10.0.20.241"
                    cron_renew_day: "1"
                ec2-3-64-155-25.eu-central-1.compute.amazonaws.com:
                    host_name: mongo-2
                    host_ip: "3.64.155.25"
                    host_private_ip: "10.0.21.199"
                    cron_renew_day: "2"
                ec2-18-156-39-39.eu-central-1.compute.amazonaws.com:
                    host_name: mongo-3
                    host_ip: "18.156.39.39"
                    host_private_ip: "10.0.22.126"
                    cron_renew_day: "3"
        primary:
            hosts:
                ec2-52-29-21-17.eu-central-1.compute.amazonaws.com:
        secondaries:
            hosts:
                ec2-3-64-155-25.eu-central-1.compute.amazonaws.com:
                    priority: 1
                ec2-18-156-39-39.eu-central-1.compute.amazonaws.com:
                    priority: 1
    vars:
        remote_user: ubuntu
        mongodb_replicaset_name: rs0
        mongodb_db_path: "/mnt/mongo_data"
        mongodb_user_user_admin_any_database_name: siteUserAdmin
        mongodb_user_user_admin_any_database_password: "strong-pwd-1"
        mongodb_user_root_name: siteRootAdmin
        mongodb_user_root_password: "strong-pwd-2"
        mongodb_main_database: siteMainDataBase
        mongodb_user_readwrite_main_database_name: "siteDataBaseUser"
        mongodb_user_readwrite_main_database_password: "strong-pwd-3"
        partitioning_device_name: "/dev/nvme0n1"
        partitioning_partition_name: "/dev/nvme0n1p1"
        partitioning_luks_passphrase: "strong-pwd-4"
        partitioning_luks_name: cryptolvm
        partitioning_vg_name: mongo_vg
        partitioning_lv_name: mongo_data
        certbot_admin_email: xyz@email.com